[package]
name = "hamster"
version = "0.0.2"
authors = ["Giles Cope <gilescope@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gitlab_ci_parser = { git = "https://github.com/gilescope/gitlab-ci-parser.git", rev="c0aa7abaa4d9b73b06c6d973ff2354ff264acf76" }
subprocess = { version="*", default_features=false }